### ISSUE TITLE
MinosField extract caster attribute to an external class

### ISSUE THREAD

**Issue by andrea-mucci** [Clariteia/minos_microservice_common#53]
Create a class for Attributes Caster

**Comment by garciparedes** [comment]
The objective of this issue is to reduce the code complexity of the `minos.common.model.ModelField` class, mostly generated in the casting step of the `value` setter. The proposed approach is to create a private `_ModelFieldCaster` class that contains the corresponding methods.

With this approach, we are able to move about 200 lines of code to an external class that could probably be moved to an external file. The new way to use old the `_cast_value` method is simply as follows:
```python
value = _ModelFieldCaster(self).cast(data)
```
