### ISSUE TITLE
ModelBase ModelRef type as Union representation

### ISSUE THREAD

**Issue by andrea-mucci** [Clariteia/minos_microservice_common#59]
Modify the ModelRef type to `Union[int, T]`

**Comment by garciparedes** [comment]
Closed by mistake

**Comment by garciparedes** [comment]
According to the recurrent doubts related with this issue, I'll proceed to include a more detailed explanation here as a comment:

# Current status:

The current implementation of the `ModelRef` acts as a wrapper of the `MinosModel` type and only adds a type validation layer. For example:

```python
class Person(Aggregate):
    name: str


class Car(Aggregate):
    owner: ModelRef[Person]
```
At runtime, is enforced that the `Car.owner` attribute is a `Person` one.

# Proposal:
The objective of this issue is to allow some kind of referencing mechanism (with a similar nature to primary - foreign key in relational database approaches) in order to be able to model the relationship between different model entities in the `minos` framework.

To do that, the natural mechanism is to extend the behaviour of the `ModelRef[T]` type (with `T` as the instance type) to be something similar to a wrapper of the `Union[T, identifier]`. Then, any `ModelRef` is defined could be the instance itself, or some kind of identifier (or foreign-key) that allows to recover the instance itself with some mechanism (to be defined).

At this point, the main problem is how to define that identifier (to be used as with a similar nature to a primary - foreign key relationship). One thing that we want to avoid is to have broken-references (that is not the same as deleted-references, which is also bad but not as bad as the first problem). 

Then, that references must have some kind of persistence, maybe at database rows (like the `Aggregate` instance, which are already uniquely identified through its `id: int` attribute). So, this proposal aims to restrict the `ModelRef` `T` type to be inheritors of `Aggregate` such that `ModelRef[T extends Aggregate] = Union[T, int]`  could be a good definition about it.

This new approach has a big caveat at this point. How could I do something like that?
```python
class Person(Aggregate):
    name: str


# MinosModel instead of Aggregate because it's not needed to be identified nor versioned, simply replaced.
class Ownership(MinosModel):  
    owner: ModelRef[Person]
    since_year: int


class Car(Aggregate):
    owners: list[ModelRef[Ownership]]
```
The problem in this case is that `Ownership` cannot be used with a `ModelRef` because doesn't inherit `Aggregate`. To solve this caveat, I propose to allow to directly use instances of `MinosModel` without the corresponding `ModelRef` to avoid any referencing schema (and always keep linked the instance). If this approach is followed, we could define the previous set of classes as follows:
```python
class Person(Aggregate):
    name: str


# MinosModel instead of Aggregate because it's not needed to be identified nor versioned, simply replaced.
class Ownership(MinosModel):  
    owner: ModelRef[Person]
    since_year: int


class Car(Aggregate):
    owners: list[Ownership]
```

Now, the `Car.owners` is a "hard" link to the `list` of `Ownership` instances because it is stored together in the database, but `Ownership.owner` is a "soft" link because only a reference (`int`) will be stored on that field in the database.

The opposite direction could also be satisfied, if we want to create a class (like `Event`) that contains a list of `Aggregate` instances in some way and we want to always have the instance (in that case, we must know what we are really doing in terms of persistence), we could do something like that:

```python
class Event(MinosModel):
    items: list[Aggregate]
```

With this approach, we could have "the best of both worlds", controlled by the user. Probably, the inter-`Aggregate` relationships should be wrapped by a `ModelRef` (and be stored "by-reference" in the database), but we could enforce the "by-value" relationships at some cases like the `Event` or `Ownership` ones.

I hope my proposal has been clarified, If @Clariteia/core-devs have any question related to that, don't doubt to ask me! 🙂
